# Generated by Django 3.2.3 on 2021-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('data', models.FileField(upload_to='')),
                ('right_answer', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
