# Generated by Django 3.2.3 on 2021-11-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answer_type',
            field=models.CharField(choices=[('SEZNAM', 'SEZNAM'), ('ČÍSLO', 'ČÍSLO'), ('TEXT', 'TEXT')], max_length=10, null=True),
        ),
    ]
