# Generated by Django 3.2.3 on 2021-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_assignment_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
